### ISSUE TITLE
Please add VERSION to cmake project()

### ISSUE THREAD

**Issue by abdes** [noloader/cryptopp-cmake#10]
```
-- *************************************************************************
The Crypto++ library does not officially support CMake. CMake support is a
community effort, and the library works with the folks using CMake to help
improve it. If you find an issue then please fix it or report it at
https://github.com/noloader/cryptopp-cmake.
-- *************************************************************************
CMake Warning (dev) at cmake-build-debug/cryptopp-src/CMakeLists.txt:19 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
    PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by noloader** [comment]
@abdes,

> Please add VERSION to cmake project...

I believe [`CmakeList.txt`](https://github.com/noloader/cryptopp-cmake/blob/master/CMakeLists.txt#L72) has it:

```
set(cryptopp_VERSION_MAJOR 7)
set(cryptopp_VERSION_MINOR 0)
set(cryptopp_VERSION_PATCH 0)
```

Maybe you can track down the issue and work up a patch.

**Comment by abdes** [comment]
The only issue bro is that make policies deprecate the setting of version numbers like above. The new way is to set the version in the project() line. The solution is very simple: set the version as following and remove the explicit setting of the version variables, which will be automatically populated by cmake:
```
project(cryptopp VERSION 7.0.0)
```
I'll send you a pull request...

**Comment by noloader** [comment]
> You just released a completely updated CMakeLists.txt with minimum requirement of cmake version 3.7.0 - this makes the issue disappear :-)

Yeah, CMake is a mess. It looks like Ubuntu 14.05 is probably broke even though it is LTS and supported through 2019:

```
CMake Error at CMakeLists.txt:22 (cmake_minimum_required):
  CMake 3.7 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
cmake failed
```

This is why I gave up on CMake. There are too many problems with it.

**Comment by abdes** [comment]
IKR :-)
Don't give up... This is what I do in my travis build script to get the latest cmake on Ubuntu:
```
#
# Build Dependencies
#
before_script:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi

  #
  # Build Folder
  #
  - mkdir _build
  - cd _build

  #
  # Update / Install CMake
  #
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      mkdir -p external/cmake
      pushd external/cmake
      wget https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.sh
      chmod +x cmake-*-Linux-x86_64.sh
      ./cmake-*-Linux-x86_64.sh --exclude-subdir --skip-license
      export PATH="${PWD}/bin:$PATH"
      popd
    else
      brew update
      brew outdated cmake || brew upgrade cmake
    fi
```

**Comment by noloader** [comment]
The idea is to work with what is on a machine. Users should be able to download the files and things "just work".

Some environments I work in do not allow the changes. Other environments require senior management to sign-off on the change control items that deviate from organization's standard image. For example, US Treasury requires a change control item approved by senior management in Treasury.

**Comment by abdes** [comment]
If you wanna downgrade the requirement to 2.7, then you know the fix for the version policy issues :-)

I've done a lot of research lately on the other alternatives to cmake, the issue is that cmake is the defect standard os of now for C++ open source projects. It also saves a lot of time generating the build files and die files for windows.

**Comment by noloader** [comment]
> I've done a lot of research lately on the other alternatives to cmake, the issue is that cmake is the defect standard os of now for C++ open source projects. It also saves a lot of time generating the build files and die files for windows.

Not for Crypto++. In essence CMake could not pass acceptance testing. Also see [CMake Removal](https://www.cryptopp.com/wiki/CMake) on the wiki. It details the problems we had with the program.

**Comment by jcfr** [comment]
Having s a dedicated project called "crypto-cmake" is great. It removes the
need to argument for or against Cmake and allow the community interested to
support to contribute changes and maintain the build system.

I then suggest we focus on that :)

Moving forward, I anticipate it will streamline not only compilation and
integration but also cross a compilation.

The other good news is that we don't need to convince anyone about it, we
can demonstrate it will work (or fail) by doing it in this project.

**Comment by abdes** [comment]
@noloader now that you have downgraded the requirement on cmake version, please at least set the cmake policy CMP0048 to OLD before the project() line in the CMakeLists.txt so that we don't get the warning on the VERSION variables. I know this is cosmetic, but it's part of having a clean build output and it clearly states your intent to stay at a lower version of cmake.

```
cmake_minimum_required(VERSION 2.8.12)
cmake_policy(SET CMP0048 OLD)

project(cryptopp)
```

**Comment by noloader** [comment]
```
cmake_minimum_required(VERSION 2.8.12)
cmake_policy(SET CMP0048 OLD)

project(cryptopp)
```

Please be sure to test the change on older versions of Cmake, like the one found on Ubuntu 14.04 LTS.

**Comment by abdes** [comment]
OK.

**Comment by noloader** [comment]
@abdes,

If you have some time could you look at [Issue 15](https://github.com/noloader/cryptopp-cmake/issues/15).

**Comment by abdes** [comment]
Ok.
Let me take a look...

**Comment by abdes** [comment]
Warning eliminated with PR #17
