### ISSUE TITLE
cryptest-cmake.sh now available

### ISSUE THREAD

**Issue by noloader** [noloader/cryptopp-cmake#14]
Hi Everyone,

`cryptest-cmake.sh` now available in `TestScripts`. The script downloads the CMake files to `$(PWD)`, creates a `build` directory, and then builds the library and executes self tests.

To use the script:

```
cd cryptopp
git pull
cp TestScripts/cryptest-cmake.sh .
./cryptest-cmake.sh
```

After the script runs the CMake files are left in place so they can be used again in the future.

There is also a `cryptest-autotools.sh` that works the same way for Autotools.

**Comment by jcfr** [comment]
It may also be sensible to enable continuous integration of pull request by doing something like this in Travis and Appveyor:

```
git clone https://github.com/weidai11/cryptopp /tmp/tmp/cryptopp-source
mkdir build && cd $_
cmake -DSRC_DIR:PATH=/tmp/tmp/cryptopp-source ../
make
ctest
```

**Comment by noloader** [comment]
@jcfr,

I enabled AppVeyor and Travis services for both Autotools and CMake.

Let me know what else you need. *noloader, gmail* account.
