### ISSUE TITLE
CMake Error at CMakeLists.txt: "STREQUAL" "SunOS"

### ISSUE THREAD

**Issue by noloader** [noloader/cryptopp-cmake#22]
I'm testing on [GCC112 on the compile farm](https://gcc.gnu.org/wiki/CompileFarm):

```
CMake Error at CMakeLists.txt:151 (if):
  if given arguments:

    "STREQUAL" "SunOS"

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
cmake failed
```

Here is the line in CmakeList.txt:

```
if (${CMAKE_SYSTEM_NAME} STREQUAL "SunOS")
  set(GREP_CMD /usr/xpg4/bin/grep)
  set(SED_CMD /usr/xpg4/bin/sed)
else()
  set(GREP_CMD grep)
  set(SED_CMD sed)
endif ()
```

ping @abdes. Would you mind taking a look at this? It looks like the break was introduced before we created this repository. The pain point here is, (1) CMake does not define the variable that is being used and (2) there's no way I know of to get a portable terminal to run commands (assuming you want to run `uname`).

Also see [GCC Compile Farm Accounts for Testing](https://github.com/noloader/cryptopp-cmake/issues/2).

**Comment by abdes** [comment]
The error simply indicates that `${CMAKE_SYSTEM_NAME}` is blank. That variable is filled with the result of `uname -s` by cmake. What does uname -s return on that particular system you used?

**Comment by abdes** [comment]
> Edit 2:
> Just pushed commit 355cee0 to fix that.
@noloader can you please verify this has been fixed and close the issue if so?

**Comment by abdes** [comment]
Solaris build fixed as of commit ed5c3deda48a101fd26c9a911d8429434775d7c7

**Comment by noloader** [comment]
Good job @abdes,

Here's the SunCC (Sun C++ compiler) test case. It works fine, too:

    cd cryptopp
    cp TestScripts/cryptest-cmake.sh .
    CXX=/opt/developerstudio12.6/bin/CC ./cryptest-cmake.sh

**Comment by abdes** [comment]
> You just poked Oracle in the eye. Distributing old components is part of Oracle's business model. Oracle charges a lot of money to access their updated software repo. Many folks have pay the extortion, but not because of Crypto++...

I've always had an issue with Sun since school days when they absolutely refused to adopt Motif as a windowing system. It has not changed for 25 years, it even became worse with Oracle. Solaris X86 is ugly, slow, and archaic, by laziness or to just lock the customers into bad stuff. BUt, like you said, we gotta do we gotta do and make the stuff people need available even for those unfortunate ones who are still locked into archaic platforms :-)
