### ISSUE TITLE
CMakeList.txt adds Python dependencies

### ISSUE THREAD

**Issue by noloader** [noloader/cryptopp-cmake#29]
I was looking through `CMakeList.txt`. I noticed `CMakeList.txt` has a Python dependency:

```
if(NOT EXISTS ${SRC_DIR}/${_landmark})
    message(FATAL_ERROR "Failed to locate python source.
The searched locations were:
   <CMAKE_CURRENT_SOURCE_DIR>
   <CMAKE_CURRENT_SOURCE_DIR>/${_extracted_dir}
   <CMAKE_CURRENT_BINARY_DIR>/../${_extracted_dir}
   <SRC_DIR>
You could try to:
  1) download cryptopp
  2) extract the archive in folder: ${_parent_dir}/${_extracted_dir}
  3) Check that file \"${_parent_dir}/${_extracted_dir}/${_landmark}\" exists.
  4) re-configure.
If you already downloaded the source, you could try to re-configure this project passing -DSRC_DIR:PATH=/path/to/Python-{PY_VERSION} using cmake or adding an PATH entry named SRC_DIR from cmake-gui.")
endif()
```

I'm mostly ignorant to CMake so forgive my knowledge gaps. We usually don't want to add additional requirements to build things. We want things to "just work" for users. Requiring users to download and install Python kind of nullifies the "it just works" we are aiming for.

**Comment by abdes** [comment]
It's not a dependency. It's a copy paste code for source directory location detection of cryptopp from python project :-)
Should be cleaned up in one of the upcoming commits...

**Comment by noloader** [comment]
Cleared at [Commit 847ff0005b66](https://github.com/noloader/cryptopp-cmake/commit/847ff0005b66).
