### ISSUE TITLE
Doesn't install cmake files

### ISSUE THREAD

**Issue by yurivict** [noloader/cryptopp-cmake#34]
In the FreeBSD port (```security/cryptopp```) I expected that the cmake-based build would install cmake files, so that other projects would be able to find it through cmake scripts.

But the list of files that it installs is identical.

Please install cmake files.

**Comment by abdes** [comment]
Can you please elaborate a bit more on what files you were looking for and where you were expecting them to be?

Currently we do install the following files in 'CMAKE_INSTALL_PREFIX/lib/cmake/cryptopp' :
  - cryptopp-config-version.cmake  
  - cryptopp-config.cmake  
  - cryptopp-targets-relwithdebinfo.cmake  
  - cryptopp-targets.cmake

**Comment by yurivict** [comment]
No, it didn't install any .cmake files at all. The plist was the same as with gnu make build.
Do .cmake files require some option to be enabled?

**Comment by abdes** [comment]
Which version of cmake are you using?
Required > 2.8.8

```
# CMake Package
if (NOT CMAKE_VERSION VERSION_LESS 2.8.8)
  include(CMakePackageConfigHelpers)
  write_basic_package_version_file("${PROJECT_BINARY_DIR}/cryptopp-config-version.cmake" VERSION ${cryptopp_VERSION_MAJOR}.${cryptopp_VERSION_MINOR}.${cryptopp_VERSION_PATCH} COMPATIBILITY SameMajorVersion)
  install(FILES cryptopp-config.cmake ${PROJECT_BINARY_DIR}/cryptopp-config-version.cmake DESTINATION "lib/cmake/cryptopp")
  install(EXPORT ${export_name} DESTINATION "lib/cmake/cryptopp")
endif ()
```

**Comment by mouse07410** [comment]
I believe this is about having/creating and installing file `FindCryptoPP.cmake` that would tell *other* CMake-based projects *where* to find CryptoPP header files and libraries.

Currently we do not create this file, though it would be great if the build process could do that.

**Comment by yurivict** [comment]
> I believe this is about having/creating and installing file FindCryptoPP.cmake

Yes, this was the whole point I tried to build with cmake.

**Comment by jcfr** [comment]
>  believe this is about having/creating and installing file FindCryptoPP.cmake 

Since the project already generates a `cryptopp-config.cmake`, there is no need for a `FindCryptoPP.cmake`.

The Find* are only useful when the upstream project doesn't generate a config file.

Here are some resources:
* Config-file vs Find-package: https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#using-packages
* Getting imported targets through `find_package`?: https://stackoverflow.com/a/35840894
* Correct way to use third-party libraries in cmake project: https://stackoverflow.com/questions/51564251/correct-way-to-use-third-party-libraries-in-cmake-project/51567322#51567322

Here is a post providing more details:

**Comment by abdes** [comment]
If I may also add to what @jcfr already mentioned above:

* cmake documentation about config-file packages (this is what is provided by cryptopp-cmake) https://cmake.org/cmake/help/v3.4/manual/cmake-packages.7.html#id11
* cmake documentation about find-module packages (not provided by cryptopp-cmake, should not be provided by upstream but made by downstream) https://cmake.org/cmake/help/v3.4/manual/cmake-packages.7.html#id12

Excerpt from the cmake documentation:

> Typically, a find module is needed when the upstream is not built with CMake, or is not CMake-aware enough to otherwise provide a package configuration file. Unlike a package configuration file, it is not shipped with upstream, but is used by downstream to find the files by guessing locations of files with platform-specific hints.

**Comment by SylvainCorlay** [comment]
>> I believe this is about having/creating and installing file FindCryptoPP.cmake
>
> Yes, this was the whole point I tried to build with cmake.

This should not generate a `FindCryptoPP.cmake` as soon as the `project-config.cmake` is generated and installed.
