### ISSUE TITLE
Add chacha-simd.cpp

### ISSUE THREAD

**Issue by noloader** [noloader/cryptopp-cmake#36]
@abdes,

We added `chacha-simd.cpp`, and provided both x86 and ARM acceleration.

Do you want to try the cut-in for x86, ARM and Aarch64?

You can test your changes with `./cryptest-cmake.sh`. `./cryptest-cmake.sh` is located in `TestScripts/`. Just copy it up to the root directory and run it.

**Comment by abdes** [comment]
Will update the cmake file to stick to sse2 for chacha-simd after the fic made to cryptopp
