### ISSUE TITLE
Missing compiler id

### ISSUE THREAD

**Issue by fxha** [noloader/cryptopp-cmake#4]
When building cryptopp on apple (compiler id `AppleClang`) the build will fail, due to missing architecture flags. This is because in [L432](https://github.com/noloader/cryptopp-cmake/blob/7ef1dbe0db095ea480500dd8e10c9ece8975974f/CMakeLists.txt#L432)

```
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
                          ^^^^^^^^
```

we expect `Clang`. The right way is to check for both of them: e.g. `CMAKE_CXX_COMPILER_ID MATCHES "Clang"`.

Furthermore,  [test headers](https://github.com/noloader/cryptopp-cmake/blob/7ef1dbe0db095ea480500dd8e10c9ece8975974f/CMakeLists.txt#L372) missing `${CMAKE_CURRENT_SOURCE_DIR}/factory.h` and [test sources](https://github.com/noloader/cryptopp-cmake/blob/7ef1dbe0db095ea480500dd8e10c9ece8975974f/CMakeLists.txt#L378) `validat4.cpp`.

----

I can't place code under Public Domain, due to german copyright restrictions. So I cannot create a pull request or is CC0 1.0 valid?

**Comment by noloader** [comment]
@mouse07410, @MarcelRaad,

Can you handle this change? I don't have CMake installed to test it.

**Comment by mouse07410** [comment]
Yeah, I can. I use CMake in a few projects (r.g., EncFS and CryFS).

BTW, I think we should consider keeping CMake-roasted stuff as a branch of the main repo.

**Comment by mouse07410** [comment]
@noloader what's your take on removing `factory.h` from the installed .h? It is used only by benchmarks and `test.cpp`.

**Comment by noloader** [comment]
@mouse07410,

> what's your take on removing factory.h from the installed .h? It is used only by benchmarks and test.cpp.

`factory.h` is kind of interesting. It is only used in the test suite at the moment. However, it does not exist in the `Test::` namespace because it can be used in regular code. For example, I have a clone that experiments with an ENGINE interface. The Engines provide an abstraction to things like Apple's CommonCrypto. I use the factory classes to get a handle to one of the engine classes.

Right now it can be removed. But I don't think it is the best choice.

**Comment by mouse07410** [comment]
OK, let's keep it in then. One .h file won't break anybody's space-bank.

Also, in the process of testing this I've hit some problems (MacOS 10.12.6). Will open another issue for those.

**Comment by mouse07410** [comment]
@fxha, thanks for your fixes. `factory.h` stays, other changes have been applied. I tested that it works.

Thanks again!
