### ISSUE TITLE
Setting DISABLE_ASM to ON breaks Visual Studio 2008 and lower builds

### ISSUE THREAD

**Issue by SamuelEnglard** [noloader/cryptopp-cmake#44]
When building using Visual Studio 2008 or lower, ASM is required. See [cpu.cpp:59](https://github.com/weidai11/cryptopp/blob/master/cpu.cpp#L59).

**Comment by SamuelEnglard** [comment]
I'm not the one who disabled it so I'll have to ask why. The problem is still there even with my fix.

**Comment by noloader** [comment]
@MarcelRaad, @abdes,

Can one of you check on this problem and advise?

I'd like to clear this issue if possible (before tagging the `CRYPTOPP_8_0_0` release).

**Comment by MarcelRaad** [comment]
As VS 2008 doesn't support inline assembly in 64-bit mode and obviously doesn't provide the required intrinsic, I don't think there's anything that can be done about that. Except maybe rejecting `DISABLE_ASM` for 64-bit with a nicer error message. To be clear, the problem doesn't exist when compiling in 32-bit mode as inline assembly is used then.

**Comment by noloader** [comment]
> As VS 2008 doesn't support inline assembly in 64-bit mode and obviously doesn't provide the required intrinsic, I don't think there's anything that can be done about that. 

Right, but we don't have the issue on VS2010 or above. Or I don't believe we do. Here's what I see when using MSBuild (I don't have a CMake machine for this test):

```
C:\Users\Jeff\cryptopp>msbuild /t:Build /p:Configuration=Debug;Platform=x64 cryptlib.vcxproj
Microsoft (R) Build Engine version 4.7.3062.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 12/28/2018 10:03:16 AM.
Project "C:\Users\Jeff\Desktop\cryptopp\cryptlib.vcxproj" on node 1 (Build targ
et(s)).
PrepareForBuild:
  Creating directory "x64\cryptlib\Debug\".
  Creating directory "x64\Output\Debug\".
...

  cryptlib.vcxproj -> C:\Users\Jeff\cryptopp\x64\Output\Debug\cryptlib.
  lib
FinalizeBuildStatus:
  Deleting file "x64\cryptlib\Debug\cryptlib.unsuccessfulbuild".
  Touching "x64\cryptlib\Debug\cryptlib.lastbuildstate".
Done Building Project "C:\Users\Jeff\cryptopp\cryptlib.vcxproj" (Build target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:51.07
```

I don't see any cross-pollination of inline ASM.

**Comment by MarcelRaad** [comment]
I'm not sure I understand the problem, but with `DISABLE_ASM`, neither x64dll.asm nor MASM are used:
https://github.com/noloader/cryptopp-cmake/blob/b97d72f083fefa249e46ae3c15a2c294e615fca2/CMakeLists.txt#L567
This leads to linker errors about missing `ExtendedControlRegister` definition.

**Comment by noloader** [comment]
> I'm not sure I understand the problem

Yeah, me too.

@SamuelEnglard, we need the command that is producing the error, and the exact error message. We can revisit this if you can provide it.

**Comment by SamuelEnglard** [comment]
@MarcelRaad summed up the issue perfectly. If `DISABLE_ASM` is set for a 64bit build you get linking errors for `ExtendedControlRegister`. I honestly don't think there is a way to really fix this on Cryptopp's side. I think the CMake just needs to not allow the combination of `DISABLE_ASM` when using the `Visual Studio 9 2008` generator targeting x64. It's simply an invalid configuration.
