### ISSUE TITLE
Cannot find source file: /usr/ports/security/cryptopp/work/cryptopp-7.0.0_1/bench3.cpp

### ISSUE THREAD

**Issue by yurivict** [noloader/cryptopp-cmake#45]
While trying in the FreeBSD port context, it fails:
```
-- Configuring done
CMake Error at CMakeLists.txt:1086 (add_executable):
  Cannot find source file:

    /usr/ports/security/cryptopp/work/cryptopp-7.0.0_1/bench3.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at CMakeLists.txt:1086 (add_executable):
  No SOURCES given to target: cryptest
```

rev. b97d72f
cryptopp-7.0.0

**Comment by noloader** [comment]
Thanks  @yurivict.

> /usr/ports/security/cryptopp/work/cryptopp-7.0.0_1/bench3.cpp

Forgive my ignorance... What version of Crypto++ distribute?

`bench3.cpp` was added recently. We took `bench1.cpp` and `bench2.cpp` and refactored them into 3 benchmark files to avoid OOM kills on low resource devices.

The tip of crpytopp-cmake follows the tip of Wei Dai's cryptopp master. If you are using 7.0, then you should keep them paired. You might want to grab the 7.0 version of CMake at [cryptopp-cmake
 | releases](https://github.com/noloader/cryptopp-cmake/releases).
