### ISSUE TITLE
Disable avx/avx2, make compilation failed

### ISSUE THREAD

**Issue by dfleury2** [noloader/cryptopp-cmake#62]
Hi,
when I deactivated avx/avx2 the compilation of cryptopp failed on (chacha_avx.cpp).
It seems that the flag --mavx (or similar) is missing and should be present event if avx if disabled.
I see it when I compile cryptopp using the Makefile provided with cryptoo.
Regards,

**Comment by noloader** [comment]
This should be fixed.
